controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
app_charts_details:
    path: /charts/
    controller: App\Controller\ChartsController::test
    methods: ['GET']

app_charts_update_scale:
    path: '/charts/updatescale'
    controller: 'App\Controller\ChartsController::updateChartScale'
    methods: ['POST']

app_charts_update_palier:
    path: '/charts/updatepalier'
    controller: 'App\Controller\ChartsController::updateChartPalier'
    methods: ['POST']

